name: Dart publish package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs: 
  test:
    runs-on: ubuntu-latest

    # Note that this workflow uses the latest stable version of the Dart SDK.
    # Docker images for other release channels - like dev and beta - are also
    # available. See https://hub.docker.com/r/google/dart/ for the available
    # images.
    container:
      image:  cirrusci/flutter:2.0.6

    steps:
      - uses: actions/checkout@v2
      
      - name: Print Dart SDK version
        run: dart --version

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get
  publish:
    runs-on: ubuntu-latest
    needs: [test]
    container: 
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code
        run: dart format .
      - uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.GOOGLE_AUTH }}
          flutter_package: true
          skip_test: true
        
