# This is a basic workflow to help you get started with Actions

name: Semantic release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    # Note that this workflow uses the latest stable version of the Dart SDK.
    # Docker images for other release channels - like dev and beta - are also
    # available. See https://hub.docker.com/r/google/dart/ for the available
    # images.
    container:
      image:  cirrusci/flutter:2.0.6

    steps:
      - uses: actions/checkout@v2

      - name: Print Dart SDK version
        run: dart --version

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            semantic-release-dart
            conventional-changelog-conventionalcommits
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Repository Dispatch Publish Event
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}
          event-type: publish-event
