name: intertravel
description: "여행사이 리메이크"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider:

  # 자동 로그인
  shared_preferences: ^2.2.3

  # UI
  image: ^4.1.7
  flutter_image_slideshow: ^0.1.6
  flutter_expandable_fab: ^2.0.0
  auto_size_text: ^3.0.0
  intl: ^0.17.0 # 시간 표시용
  expandable_bottom_bar:
    path: localPackage/expandable-bottom-bar-master #3.22 이후로 지원불가!
  font_awesome_flutter: ^10.7.0

  image_picker: ^1.1.0
  material_dialogs: ^1.1.4
  photo_view: ^0.15.0
  extended_text_field: ^15.0.0

  # Map Plugin
  geolocator: ^11.0.0
  flutter_naver_map: ^1.2.2+flutter3.22

  # Permission
  permission_handler: ^11.3.0

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.10
  firebase_app_check: ^0.2.2+5
  flutter_dotenv: ^5.1.0

  flutter_staggered_grid_view: ^0.7.0
  draggable_bottom_sheet: ^1.0.2
  flutter_svg:
  flutter_markdown: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/user.png
    - assets/images/marker.png
    - assets/images/myPosition.png
    - .env
    - assets/appainter_theme.json

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf