name: intertravel
description: "여행사이 리메이크"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider:

  # UI
  image: ^4.1.7
  flutter_image_slideshow: ^0.1.6
  flutter_expandable_fab: ^2.0.0
  intl: ^0.17.0

  # Map Plugin
  geolocator: ^11.0.0
  flutter_naver_map: ^1.2.1

  # Permission
  permission_handler: ^11.3.0

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.10




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/user.png
