// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Okg8Hq7y9tkvvXwfgzBKNqaJAd4m2YI',
    appId: '1:983897180404:android:0d689881c2012034e5f6a1',
    messagingSenderId: '983897180404',
    projectId: 'intertravel-fab82',
    storageBucket: 'intertravel-fab82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJkj-jnZU9QtQ0yq-tCB3P11TvhMWVJrw',
    appId: '1:983897180404:ios:49ebf3b0ae9ead80e5f6a1',
    messagingSenderId: '983897180404',
    projectId: 'intertravel-fab82',
    storageBucket: 'intertravel-fab82.appspot.com',
    androidClientId: '983897180404-9sguv0n72auo4vq9tbn34gfueuhlp13k.apps.googleusercontent.com',
    iosClientId: '983897180404-811hrr26pojje060550hof173814grcp.apps.googleusercontent.com',
    iosBundleId: 'com.remake.intertravel',
  );
}
