// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCbpYLYcQzLgzKxZ_xkeDg7fyX2Cp3XBw',
    appId: '1:983897180404:web:f550ab918606c409e5f6a1',
    messagingSenderId: '983897180404',
    projectId: 'intertravel-fab82',
    authDomain: 'intertravel-fab82.firebaseapp.com',
    storageBucket: 'intertravel-fab82.appspot.com',
    measurementId: 'G-W4YPFLGEYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDekrtagx1bJBnjVnlLDvRlcDJICKvZZQ',
    appId: '1:983897180404:android:0d689881c2012034e5f6a1',
    messagingSenderId: '983897180404',
    projectId: 'intertravel-fab82',
    storageBucket: 'intertravel-fab82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJkj-jnZU9QtQ0yq-tCB3P11TvhMWVJrw',
    appId: '1:983897180404:ios:49ebf3b0ae9ead80e5f6a1',
    messagingSenderId: '983897180404',
    projectId: 'intertravel-fab82',
    storageBucket: 'intertravel-fab82.appspot.com',
    iosClientId: '983897180404-811hrr26pojje060550hof173814grcp.apps.googleusercontent.com',
    iosBundleId: 'com.remake.intertravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJkj-jnZU9QtQ0yq-tCB3P11TvhMWVJrw',
    appId: '1:983897180404:ios:0debadf3eb598b0ae5f6a1',
    messagingSenderId: '983897180404',
    projectId: 'intertravel-fab82',
    storageBucket: 'intertravel-fab82.appspot.com',
    iosClientId: '983897180404-ir6bulvhu03irpsgcvbvkq84krq4t3aj.apps.googleusercontent.com',
    iosBundleId: 'com.remake.intertravel.RunnerTests',
  );
}
